name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: thumbv8m.main-none-eabihf
    - name: cargo check  Raspberry Pi Pico 2
      run: cargo --config examples/rp235x/.cargo/config.toml check -p rp235x
